// Fenerbahçe crest, traced cell by cell from Kaan's pixel pattern
// (0b633835bc93abc72fd9d1956d6a95fd.jpg). k black · r red · b navy · y yellow · g green · . empty
export const FENERBAHCE_PIXELS = [
  '..........kkkkkkk..........',
  '........kkrrrbrrrkk........',
  '......kkrrrrbbbrrrrkk......',
  '.....krrrrrbbbbbrrrrrk.....',
  '....krrrrrbbbbbbbrrrrrk....',
  '...krrrrrbbbbbbbbbrrrrrk...',
  '..krrrrrbbbbbbbbbbbrrrrrk..',
  '.krrrrbbbbbbbbbbbbbbbrrrrk.',
  '.krrrbbbbbbbbbbbbbbbbbrrrk.',
  'kryyyyyyyyyyygyyyyyyyyyyyrk',
  'kryyyyyyyyyyygyyyyyyyyyyyrk',
  'krryyyyyyyyygggyyyyyyyyyrrk',
  'krryyyyyyyygggggyyyyyyyyrrk',
  'krryyyyyyyygggggyyyyyyyyrrk',
  'krrryyygyyygggggyyygyyyrrrk',
  'krrrbbbggbbbgggbbbggbbbrrrk',
  'krrrbbbgggbbgggbbgggbbbrrrk',
  'krrrbbbbbbgbbgbbgbbbbbbrrrk',
  'krrrrbggbbbgbgbgbbbgggbrrrk',
  '.krrrbgggbbbgggbbbgggbbrrk.',
  '.krrrbbgggbbbgbbbggggbbrrk.',
  '..krrrrbgggbbgbbggggbrrrk..',
  '...krrrrbggbbgbbggbbrrrk...',
  '....krrrrbbgggggbbbrrrk....',
  '.....krrrrbbbgbbrrrrrk.....',
  '......kkrrbbbgbbrrrkk......',
  '........kkbbbgbbrkk........',
  '..........kkkkkkk..........',
]
